// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seneokuwpvegzgqlolyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbmVva3V3cHZlZ3pncWxvbHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxOTk0MjIsImV4cCI6MjA3NDc3NTQyMn0._lSUJqy94Ah7j028hKZWCkyNY4PTzhvT_eMcSdXbnRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});